name: border_shadow
description: Adds shadows (glowing) to text fields and buttons in a Flutter application.
version: 0.0.1
repository: https://github.com/astoniocom/border_shadow
issue_tracker: https://github.com/astoniocom/border_shadow/issues
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
